name: helpers
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  formz: ^0.6.0
  http: ^0.13.5
  http_parser: ^4.0.2
  url_launcher: ^6.1.11
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.1.0
  equatable: ^2.0.5
  intl: ^0.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  faker: ^2.1.0
