name: amandaleme_personal_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+4

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.4
  # flow_builder: ^0.0.9
  http: ^0.13.5
  shared_preferences: ^2.1.0
  formz: ^0.6.0
  google_fonts: ^4.0.3
  video_player: ^2.6.1
  path_provider: ^2.0.15
  intl: ^0.18.1
  social_share: ^2.3.1
  lottie: ^2.3.2
  flutter_dotenv: ^5.1.0
  shimmer: ^3.0.0
  image_picker: ^1.0.8
  url_launcher: ^6.1.11


# Ours Packages
  repositories:
    path: packages/repositories
  helpers:
    path: packages/helpers
  video_preparation_service:
    path: packages/video_preparation
  phosphor_flutter: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logos/logo-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logos/
    - assets/images/gyms/
    - assets/images/icons/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
