name: amandaleme_personal_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  flow_builder: ^0.0.9
  http: ^0.13.5
  shared_preferences: ^2.1.0
  formz: ^0.6.0
  google_fonts: ^4.0.3
  video_player: ^2.6.1
  intl: ^0.18.1



# Ours Packages
  workoutsheet_repository:
    path: packages/workoutsheet_repository
  authentication_repository:
    path: packages/authentication_repository
  company_repository:
    path: packages/company_repository
  http_adapter: 
    path: packages/http
  cache_adapter:
    path: packages/cache
  form_inputs:
    path: packages/form_inputs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logos/
    - assets/images/gyms/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
