name: amandaleme_personal_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  flow_builder: ^0.0.9
  http: ^0.13.5
  localstorage: ^4.0.1+2



# Ours Packages
  authentication_repository:
    path: packages/authentication_repository
  http_adapter: 
    path: packages/http
  cache_adapter:
    path: packages/cache

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
