name: authentication_repository
description: Dart package which manages the user domain.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  local_auth: ^2.1.6
  http_adapter:
    path: ../http
  cache_adapter:
    path: ../cache
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0