name: repositories
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  # sdk: ^3.1.3
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  path_provider: ^2.1.4
  equatable: ^2.0.5
  http_parser: ^4.1.0
  http: ^1.2.2
  flutter:
    sdk: flutter
  local_auth: ^2.3.0
  collection: ^1.19.0
  helpers:
    path: ../helpers

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

dependency_overrides:
  collection: ^1.19.0