name: repositories
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  path_provider: ^2.0.15
  equatable: ^2.0.5
  http_parser: ^4.0.2
  http: ^0.13.5
  flutter:
    sdk: flutter
  local_auth: ^2.1.6
  helpers:
    path: ../helpers

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
