default_platform(:ios)

platform :ios do
  desc "Build and deploy to TestFlight"
  lane :deploy do
    # Configurar SSH para acessar o repositório de certificados
    sh("echo \"#{ENV['SSH_PRIVATE_KEY_CERT_REPO']}\" > /tmp/deploy_key")
    sh("chmod 600 /tmp/deploy_key")
    sh("eval $(ssh-agent -s)")
    sh("ssh-add /tmp/deploy_key")
    sh("ssh-keyscan github.com >> ~/.ssh/known_hosts")

    # p12_path = "/tmp/certificado.p12"
    # File.open(p12_path, "wb") do |file|
    #   file.write(Base64.decode64(ENV['CERTIFICATE_PERSONAL_P12']))
    # end

    # # Importando o certificado para o Keychain
    # sh("security import #{p12_path} -P #{ENV['P12_PASSWORD']} -A -t cert -f pkcs12 -k ~/Library/Keychains/login.keychain-db")

    api_key = app_store_connect_api_key(
      key_id: 'JS3MYV9HPQ',
      issuer_id: '513d5581-7fd6-470a-8e83-f2f97820b525',
      key_content: ENV['APP_STORE_CONNECT_API_KEY'],
      is_key_content_base64: true,
    )

    match(
      type: "appstore",
      api_key: api_key,
      # keychain_name: "login.keychain-db",
      keychain_password: ENV['MATCH_PASSWORD']
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.bcsgarcia.personal-app-amanda-leme" => "match AppStore com.bcsgarcia.personal-app-amanda-leme"
        }
      }
    )

    # sync_code_signing(
    #   type: "appstore",
    #   api_key: api_key,
    #   readonly: true,
    # )

    # pubspec = File.read("../../pubspec.yaml")
    # version = pubspec.match(/version: (\d+\.\d+\.\d+\+\d+)/)[1]

    # # Separar versão e número de build
    # version_name, version_code = version.split("+")

    # Dir.chdir "../.." do
    #   puts "*** Build flutter iOS release for version #{version_name}+#{version_code} ***"
    #   sh("flutter", "build", "ipa", "--release", "--build-number=#{version_code}", "--build-name=#{version_name}", "--target=lib/main/main.dart")
    # end

    # build_app(
    #   skip_build_archive: true,
    #   archive_path: "../build/ios/archive/Runner.xcarchive",
    # )

    upload_to_testflight(
      api_key: api_key
    )
  end

end