default_platform(:ios)

platform :ios do
  desc "Build and deploy to TestFlight"
  lane :deploy do
    match(type: "appstore")

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.bcsgarcia.personal_app.amanda_leme" => "match AppStore com.bcsgarcia.personal_app.amanda_leme"
        }
      }
    )

    upload_to_testflight
  end
end