name: launcher_adapter
description: Dart package which manages the launcher requests
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  equatable: ^2.0.5
  url_launcher: ^6.1.11
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  faker: ^2.1.0