name: video_preparation_service
description: Dart package which manages videos of the workout.
version: 1.0.0
publish_to: none

environment:
  # sdk: '>=2.19.5 <3.0.0'
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  repositories:
    path: ../repositories
  helpers:
    path: ../helpers
  path_provider: ^2.1.4
  video_player: ^2.9.1
  collection: ^1.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

dependency_overrides:
  collection: ^1.19.0