name: video_preparation_service
description: Dart package which manages videos of the workout.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  home_repository:
    path: ../home_repository
  path_provider: ^2.0.15
  
    
  video_player: ^2.6.1
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0