# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build the release APK"
  lane :build_release do
    sh("flutter", "clean")
    sh("chmod", "777", "make_install.sh")
    sh("make_install.sh")
    sh("flutter", "build", "apk", "--release", "--target=lib/main/main.dart")
    # O APK estará no caminho padrão de saída, a menos que você especifique outro
  end

  desc "Deploy to the Google Play"
  lane :deploy do
    build_release # Chama a lane definida acima para fazer o build
    upload_to_play_store(
      track: 'alpha', # Ou beta, production, etc., dependendo do seu caso de uso
      #apk: 'build/app/outputs/flutter-apk/app-release.apk' # Caminho para o seu APK
      json_key_data: ENV["GOOGLE_CLOUD_CREDENTIALS"], # Usa a variável de ambiente
      aab: '../build/app/outputs/bundle/release/app-release.aab', # Caminho para o seu AAB
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
