name: Deploy to Play Store

on:
  push:
    branches:
      - main

jobs:
  android-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.13.6' # Especifica a versão do Flutter

    - name: Set up Java Environment
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Decode keystore
      run: |
        echo "${{ secrets.KEY_JKS_BASE64 }}" | base64 -d > ./android/app/key.jks

    # - name: Build and Sign APK
    #   env:
    #     KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    #     KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
    #     STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    #   run: |
    #       cd android
    #       ./gradlew assembleRelease

    - name: Create .env-dev file
      run: |
        echo "API_BASE_URL=${{ vars.API_BASE_URL }}" >> .env
        echo "APP_PATH=${{ vars.APP_PATH }}" >> .env
        echo "GET_MEET_APP_PATH=${{ vars.GET_MEET_APP_PATH }}" >> .env
        echo "APP_HOME_PATH=${{ vars.APP_HOME_PATH }}" >> .env
        echo "NOTIFICATION_PATH=${{ vars.NOTIFICATION_PATH }}" >> .env
        echo "WORKOUTSHEET_PATH=${{ vars.WORKOUTSHEET_PATH }}" >> .env
        echo "WORKOUT_PATH=${{ vars.WORKOUT_PATH }}" >> .env
        echo "AUTH_PATH=${{ vars.AUTH_PATH }}" >> .env
        echo "REFRESH_TOKEN_PATH=${{ vars.REFRESH_TOKEN_PATH }}" >> .env
        echo "SCREEN_PATH=${{ vars.SCREEN_PATH }}" >> .env
        echo "UPDATE_UNREAD_NOTIFICATION_PATH=${{ vars.UPDATE_UNREAD_NOTIFICATION_PATH }}" >> .env
        echo "ALL_MEDIA_SYNC_PATH=${{ vars.ALL_MEDIA_SYNC_PATH }}" >> .env
        echo "CHANGE_PASS_PATH=${{ vars.CHANGE_PASS_PATH }}" >> .env
        echo "FEEDBACK_PATH=${{ vars.FEEDBACK_PATH }}" >> .env
        echo "WORKOUTSHEET_DONE_PATH=${{ vars.WORKOUTSHEET_DONE_PATH }}" >> .env
        echo "MY_MEDIAS_DIRECTORY_PATH=${{ vars.MY_MEDIAS_DIRECTORY_PATH }}" >> .env
        echo "COMPANY_ID=${{ vars.COMPANY_ID }}" >> .env

    - name: Install Fastlane
      run: sudo gem install fastlane

    - name: Run Fastlane
      working-directory: ./android/fastlane # Substitua pelo caminho correto, se necessário
      env:
        GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
        FASTLANE_GIT_EMAIL: ${{ vars.GIT_EMAIL }}
        FASTLANE_GIT_NAME: ${{ vars.GIT_USER_NAME }}
        GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: fastlane android deploy

    - name: Commit version bump
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git commit -am "Bump version number [skip ci]"
        git push
      if: success() && env.GITHUB_REF == 'refs/heads/main'
