name: Deploy to App Store

on:
  push:
    branches:
      - ios-deploy-test

jobs:
  ios-build-and-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Set up Fastlane
        run: gem install fastlane

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Set up keychain
        run: |
          security create-keychain -p "action" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "action" build.keychain
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      # - name: Import certificates
      #   run: |
      #     echo "${{ secrets.APPLE_CERTIFICATE }}" | base64 --decode > apple.cer
      #     echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > profile.mobileprovision
      #     security import apple.cer -k ~/Library/Keychains/build.keychain -T /usr/bin/codesign
      #     mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
      #     cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      #   env:
      #     APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
      #     PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}

      - name: Build and Deploy
        working-directory: ./ios/fastlane
        run: fastlane ios deploy
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}